version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    environment:
      DATABASE_URL: postgres://myuser:mypassword@database:5432/mydatabase
      PHOTOS_BUCKET: mybucket
      AWS_REGION: us-east-1
    volumes:
      - ./packages/api:/usr/src/app
    depends_on:
      - database
    networks:
      - app-network
    expose:
      - "3001"

  admin:
    build:
      context: .
      dockerfile: ./packages/admin/Dockerfile
    volumes:
      - ./packages/admin:/usr/src/app
    depends_on:
      - api
    networks:
      - app-network
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
